### ISSUE TITLE
Add method for validating tokens for the QuoteConnector

### ISSUE THREAD

**Issue by ejfasting** [SuperOffice/SuperOffice.SystemUser.Client#7]
Related to issue on [SuperOffice.Connector-samples](https://github.com/SuperOffice/SuperOffice.Connector-samples/issues/1). 

This package should contain a method that can be used by a quoteconnector. The package expects, and validates, the `.../Identity/Serial`, which is not present in the token passed inn to `IIntegrationServiceConnectorAuth.Authenticate`. 

Suggest adding method similar to how it's implemented in the [connector-sample](https://github.com/SuperOffice/SuperOffice.Connector-samples/blob/b64c700412ff77e2d0be51b6eb5e48bb08cd09a8/SuperOffice.Connector.Blazor/Utils/OAuthHelper.cs#L76).

Could possibly add a new class and/or enum to support typeOf Application, which could be `QuoteConnector`, `Application` and `ERPConnector` (still unknown if ERPConnector is different from QuoteConnector).

New method should just accept an additional variable:
`public TokenValidationResult ValidateSuperOfficeTokenAsync(string token, ApplicationType type){}`

**Comment by SuperOfficeDevNet** [comment]
Integration services do JWT validation differently then OpenID Connect. 

The JWT validation for Integration services (DB Mirroring, Quote and ERPSync Connectors) is [well-documented in the database mirroring authentication repo](https://github.com/SuperOffice/devnet-database-mirroring-authentication/blob/main/Source/DatabaseMirroringAuthentication/Validator.cs). See the [README](https://github.com/SuperOffice/devnet-database-mirroring-authentication/blob/main/Source/DatabaseMirroringAuthentication/README.md).
